site_name: 计算均质化方法
site_author: 邱小伙
site_description: 计算固体力学中均质化方法的理论

theme:
  name: material
  language: zh
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - header.autohide
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式

plugins:
  - search:
      lang:
        - zh
        - en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

nav:
  - 首页: index.md
  - 计算均质化及降阶方法:
      - 简介: _roh/index.md
      - 多尺度问题描述: _roh/chap1_基础/intro.md
      - 渐进均质化: _roh/chap1_基础/sec1_theory/asymptotic.md
      - 降阶方法:
          - 均匀场变换分析: _roh/chap1_基础/sec1_theory/tfa.md
          - 细观力学: _roh/chap1_基础/sec3_rom_diff/mmech.md
          - 非均匀场变换分析: _roh/chap1_基础/sec3_rom_diff/ntfa.md
          - 快速傅立叶变换: _roh/chap1_基础/sec3_rom_diff/fft.md
          - 聚类分析: _roh/chap1_基础/sec3_rom_diff/ca.md
      - 影响张量的计算与应用:
        - 线下求解影响张量: _roh/chap1_基础/sec2_compt_fwork/offline.md
        - 线上组装降阶方程: _roh/chap1_基础/sec2_compt_fwork/online.md
  - 细观力学:
      - 简介: _mmech/index.md
      - 弹性材料的对称性:
          - 对称性的分类: _mmech/材料和几何的对称性/0-对称性的分类.md
          - 一般各向异性: _mmech/材料和几何的对称性/1-一般各向异性.md
          - 单斜对称性: _mmech/材料和几何的对称性/2-单斜对称性.md
          - 横观各向同性: _mmech/材料和几何的对称性/6-横观各向同性.md
          - 各向同性: _mmech/材料和几何的对称性/8-各向同性.md
      - Eshelby 张量的计算方法:
          - Eshelby 张量的表示方法: _mmech/Eshelby-张量的计算方法/Eshelby-张量的表示方法.md
          - Eshelby 张量的解析公式: _mmech/Eshelby-张量的计算方法/Eshelby-张量的解析公式.md
          - Eshelby 张量的数值计算: _mmech/Eshelby-张量的计算方法/Eshelby-张量的数值计算.md
      - 等效模量的估计方法:
          - 简介: _mmech/等效模量的估计方法/简介.md
          - 稀疏法: _mmech/等效模量的估计方法/稀疏法.md
          - Mori-Tanaka 法: _mmech/等效模量的估计方法/Mori--Tanaka-法.md
          - 自洽法: _mmech/等效模量的估计方法/自洽法.md
          - 微分法: _mmech/等效模量的估计方法/微分法.md
      - 等效模量的上下界:
          - 变分原理的对偶问题: _mmech/等效模量的上下界/变分原理的对偶问题.md
          - Hashin--Shtrikman 变分原理的表述: _mmech/等效模量的上下界/HS-变分原理的表述.md
          - Hashin--Shtrikman 变分原理的构造方法: _mmech/等效模量的上下界/HS-变分原理的构造方法.md
      - 特殊几何域的解析解:
          - 圆球异质: _mmech/特殊几何域的解析解/圆球异质.md
          - 复合胞元: _mmech/特殊几何域的解析解/复合胞元.md
          - 层合板: _mmech/特殊几何域的解析解/层合板.md
  - 单胞几何建模和网格生成:
      - 简介: _ucgmsh/index.md
  - 计算非弹性:
      - 简介: _inelas/index.md
      - 连续介质力学中的热力学定律: _inelas/连续介质力学中的热力学定律.md
      - 广义标准材料框架: _inelas/广义标准材料模型.md
      - Lemaitre 塑性-损伤耦合模型: _inelas/塑性-损伤耦合的本构模型.md
      - Gurson 塑性模型: _inelas/Gurson-模型.md
      - Christensen 各向同性材料失效准则: _inelas/各向同性材料失效准则.md

draft_docs: |
  _roh/附录
  _roh/chap0_介绍/intro.md
  _roh/chap2_修正/sec1_incomp_infl_func_theory/弹塑性离散变分原理.md
  _mmech/其它
  _mmech/材料和几何的对称性/3-正交各向异性.md
  _math/Gateaux-导数与-Frechet-导数.md
